// <auto-generated />
using System;
using CalculadoraEvolucaoSaldoEvo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraEvolucaoSaldoEvo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520205704_InicialEvoSemAuth")]
    partial class InicialEvoSemAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CalculadoraEvolucaoSaldoEvo.Domain.Entities.Evolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Juro")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("Evolucoes", (string)null);
                });

            modelBuilder.Entity("CalculadoraEvolucaoSaldoEvo.Domain.Entities.LogSimulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LogsSimulacoes", (string)null);
                });

            modelBuilder.Entity("CalculadoraEvolucaoSaldoEvo.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deletado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeletadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalJuros")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("CalculadoraEvolucaoSaldoEvo.Domain.Entities.Evolucao", b =>
                {
                    b.HasOne("CalculadoraEvolucaoSaldoEvo.Domain.Entities.Simulacao", "Simulacao")
                        .WithMany("Evolucoes")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("CalculadoraEvolucaoSaldoEvo.Domain.Entities.Simulacao", b =>
                {
                    b.Navigation("Evolucoes");
                });
#pragma warning restore 612, 618
        }
    }
}
